#!/usr/bin/env sh
set -e

STAGED_FILES="$(git diff --cached --name-only --diff-filter=ACMR)"

pnpm format:all

if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | while IFS= read -r file; do
    if [ -e "$file" ]; then
      git add "$file"
    fi
  done
fi

pnpm check
